name: 'Release chief'
description: A Github Action for creating branch
branding:
  color: yellow
  icon: arrow-up
inputs:
  dryRun:
    description: If true will only calculate release version without publishing
    required: false
    default: false
runs:
  using: 'node16'
  main: 'index.js'
outputs:
  version:
    description: Semantic release version of release
