name: 'Release chief'
description: A Github Action for creating branch
branding:
  color: yellow
  icon: arrow-up
inputs:
  dryRun:
    description: If true will only calculate release version without publishing
    required: false
    default: false
runs:
  using: 'node16'
  main: 'index.js'
outputs:
  version:
    description: Semantic release version of release
  url:
    description: Last release github url
  prevVersion:
    description: Previews release version
  type:
    description: Release type (patch, minor, major)
  notes:
    description: The release notes
